title: <center>Seth Goldfarb<br>Content Marketer</center> # your name (or website title) here
<center> logo: /images/image (1).png?raw=true</center> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Seth Goldfarb helps businesses and their audiences market and understand emerging technologies.
  
theme: jekyll-theme-minimal
google_analytics: UA-38411253-7 # your Google Analytics tracking ID here
