title: <center>Seth Goldfarb<br>✏️<br>Content Marketing</center> # your name (or website title) here
logo: </images/Pb4wqjnC_400x400.jpg?raw=true border-radius=50%> # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Making helpful startups more accessible
  <br>
  <center><a href="https://www.linkedin.com/in/asethgoldfarb/">LinkedIn</a></center>
  <br>
  <center><a href="https://twitter.com/GoldenChaosGod">Twitter</a></center>
  
theme: jekyll-theme-minimal
google_analytics: UA-38411253-7 # your Google Analytics tracking ID here
