title: Seth Goldfarb<br>Marketing # your name (or website title) here
tagline: The portfolio of Seth Goldfarb
url: sethgoldfarbthewriter.com
logo: /images/image (1).png?raw=true # your photo (or logo) here
description: Finding markets for emerging technologies # your text below (remove <br> elements if you don't need line breaks)
plugins:
  - jekyll-sitemap
  - Jekyll-SEO-Tag
theme: jekyll-theme-minimal
google_analytics: UA-38411253-7 # your Google Analytics tracking ID here
