title: Seth Goldfarb ✏️ Content Marketing # your name (or website title) here
logo: "/images/Pb4wqjnC_400x400.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Making helpful startups more accessible
  <br><br>
  Seth Goldfarb is a marketing professional on a mission to accelerate the adoption of technologies that serve people. In addition to
  helping Evernym develop the business case for self-sovereign identity, Seth has published over 37,000 words on blockchain and distributed
  ledger technologies in 2019 in publications including Hacker Noon, CryptoSlate, Decrypt, and CoinReview and supports the greater c
  ommunity through his work with pnwblockchain.com and defi.school.
  <br><br>
  <a href="https://www.linkedin.com/in/asethgoldfarb/">View My LinkedIn</a>
  <br><br>
  <a href="https://twitter.com/GoldenChaosGod">View My Twitter</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
